### PR TITLE
Getting the generated document string to be more detail.

### LINKED ISSUE #371: [TS2.2.x] Operator '!==' cannot be applied to types
#### What type of issue are you creating?
- [x] Bug

#### What version of this module are you using?
- [x] 2.1.0-rc.8.3

#### Please add a description for your issue:

When running the generated SDK in a project with TypeScript 2.2.1 it results in an error:

```
ERROR in /Users/beeman/workspace/scratch/loopback-scratch/client/src/app/shared/sdk/services/core/search.params.ts (34,42): Operator '!==' cannot be applied to types '"string" | "number" | "boolean" | "symbol" | "undefined" | "object" | "function"' and '"array"'.)
/Users/beeman/workspace/scratch/loopback-scratch/client/src/app/shared/sdk/services/core/search.params.ts (37,50): Operator '===' cannot be applied to types '"string" | "number" | "boolean" | "symbol" | "undefined" | "object" | "function"' and '"array"'.)
```

There is an example project [here](https://github.com/beeman/loopback-scratch).

#### Workaround

Downgrade the Angular app to TypeScript 2.1.6.

### PR DESCRIPTION
**Pull request by lygstate**
#### What type of pull request are you creating?
- Enhancement

#### How many unit test did you write for this pull request?
0
Write a reason if none (e.g just fixed a typo):

fixes  #371 

#### Please add a description for your pull request:

### CODE REVIEW

**Comment by jonathan-casarrubias** [comment]
@lygstate thanks for this pull request, I just have a question

Your modifications when building the query params works in every scenario? also there are other pull requests that have conflicts with it, maybe an integration of all the fixes could help.

Thoughts?

**Comment by lygstate** [comment]
Yes, I also fixes #371

**Comment by lygstate** [comment]
I am not just fixes the warning, but also fixes bug in that.

**Comment by jonathan-casarrubias** [comment]
I see, then I believe we can keep the other to fix 371 and keep yours for the warnings, is that fair for you? or you believe we should take your fix?

**Comment by lygstate** [comment]
@jonathan-casarrubias Other for fix 371? You should take mine fixes, As I state, the other pull request just hidden the TypeScript warning(error report). This one is the real fix, use Array.isArray(value) instead of typeof value === 'array'

**Pull request closed without merging**
