### PR TITLE
Added a better algorithm for property detection

### PR DESCRIPTION
**Pull request by tfiwm**
Hi this is not the final pull request but i want to open it for discussions.
I rewrote the way how properties have been detected.

One point is open for me and this is the GeoPoint data type -> What do you think about if we can provide the type as GeoPoint.ts file too? An Interface and class ready to use.

[Bug-Ticket](https://github.com/mean-expert-official/loopback-sdk-builder/issues/174)

### CODE REVIEW

**Comment by jonathan-casarrubias** [comment]
Hey thanks for this contribution I think it sounds like a good Idea, maybe for now in base models. Ill review tomorrow in the office. 

Cheers

**Comment by tfiwm** [comment]
Hi Jonathan,

i fixed an other issue with unknown types which came up if you use different connectors. For me it was the mongo connector which gave me back an function ObjectID() {} .....
So i fixed it now to a fixed list which are supported by loopback.

**Comment by jonathan-casarrubias** [comment]
LGTM, could you please make the pull request from development to development instead of master?

Also if you can add test cases for your changes, looks like nothing is broken because travis does not complain, but would be better if we make sure these new features work with future changes.

Cheers
Jon

**Comment by tfiwm** [comment]
Ok i merged it into development branch and created a new pull request. You can closed this one now and refer to the other one.

Thanks and best regards

**Pull request closed without merging**
