### PR TITLE
Fix crash with angular-cli (webpack)

### PR DESCRIPTION
**Pull request by Boffka**

### CODE REVIEW

**Comment by jonathan-casarrubias** [comment]
@Boffka thanks for your pull request, could you elaborate a little about this by creating an issue? 

The unit tests that are inside the tests/angular2 are using the latest version of angular-cli and webpack and do not present these crashes.

I'm trying to make this clear because there is in the roadmap a refactor in both index and sdk.module in order to use a function to build the imports like the models imports and services imports and not within the template using logic.

But I think your input is valuable in order to know if tweaks are needed during the refactor.

Btw. Is great to see you involved in this project!!!

Cheers,
Jon

**Comment by jonathan-casarrubias** [comment]
@Boffka ok I think your issue is related to this https://github.com/mean-expert-official/loopback-sdk-builder/wiki/Known-Issues#2--deep-barrels-wont-load-when-using-webpack

**Comment by Boffka** [comment]
Exactly!

I've been watching your work on this project and would like to thank!

Special thanks for your blog. Example your application (native-chat-example) was for me a good start in NativeScript world! 

Cheers,
Boffka

**Comment by gvsdan** [comment]
I think i have this issue #97

**Comment by jonathan-casarrubias** [comment]
@gvsdan it is actually a differnt issue, @Boffka was able to generate the sdk but the crach was during the build because unreachable portions of the SDK.

Yours is during the sdk generation, but first of all it seems you still have the node_modules/loopback-sdk-builder installed, you will need to remove that one and install the @mean-expert/loopback-sdk-builder that will install in the following directory: node_modules/@mean-expert/loopback-sdk-builder.

I will add a documentation section in order to update to 2.0.0 stable.

Cheers!
Jon

**Comment by jonathan-casarrubias** [comment]
@Boffka Thanks for the contribution I will tweak it and land it under version 2.0.1.

Btw. I really appreaciate your words, it is great to know that my work and articles are helping people do amazing things!!!

Stay around, there is plenty to come.

Cheers!!!
Jon

**Comment by jonathan-casarrubias** [comment]
This patch introduced a new bug where in angular-cli.webpack-2 throws a prototype issue.

**Comment by jonathan-casarrubias** [comment]
For future reference:

WebPack is not so Barrels friendly, therefore we won't be able to load everything from './shared'; as we were doing before RC5 and SystemJS.

For anyone having issues please with WebPack, please follow the WIKI documentation carefully and import files from;

For Models: shared/sdk/models 
For Services: shared/sdk/services

IMPORTANT: Do not try to load everything from ./shared when using webpack.

**Pull request merged**
