### PR TITLE
(WIP) Ngrx orm (do not merge)

### PR DESCRIPTION
**Pull request by JonnyBGod**
#### What type of pull request are you creating?
- [ ] Bug Fix
- [x] Enhancement
- [ ] Documentation

#### How many unit test did you write for this pull request?

Write a reason if none (e.g just fixed a typo):

#### Please add a description for your pull request:

### CODE REVIEW

**Comment by JonnyBGod** [comment]
close in favor of (https://github.com/mean-expert-official/loopback-sdk-builder/pull/489)

**Comment by JonnyBGod** [comment]
@jonathan-casarrubias Sorry this was not supposed to be merged. Was an old branch, I was keeping it open just for the sake of following the discussion.

**Comment by jonathan-casarrubias** [comment]
Ok my bad, I thought this also needed to be merged, we'll need to rollback that merge

**Comment by jonathan-casarrubias** [comment]
This was confusing, actually I didn't merge this PR, it seems a commit from this PR was merged from the other PR... But this is not actually merged, I can not revert since is not merged lol

**Comment by jonathan-casarrubias** [comment]
@JonnyBGod this is confusing, I believe this PR is not merged, I can not revert since is not directly merged, what it says at the top is that 53 commits where merged from JonnyBGod:ngrx-orm, I think these commits were merged from the other PR? isn't ?

**Comment by jonathan-casarrubias** [comment]
Mh not sure :( https://github.com/mean-expert-official/loopback-sdk-builder/pull/489 this one does show the revert button, but not this one and it does say merged...

**Comment by JonnyBGod** [comment]
Ok no worries apparently everything is working fine it was probably considered as merged because all its commits were part of the other branch as well.

**Pull request merged**
