### PR TITLE
NGRX && ORM

### PR DESCRIPTION
**Pull request by JonnyBGod**
#### What type of pull request are you creating?
- [ ] Bug Fix
- [x] Enhancement
- [ ] Documentation

#### How many unit test did you write for this pull request?
15

#### Please add a description for your pull request:
Generators for NGRX Actions, Effects and Reducers;
Bonus: Guards and Resolvers;
Super Bonus: ORM.

Known limitations:
ATM ORM does not include "hasAndBelongsToMany", "hasManyThrough" relations and does not deal with polymorphic relations.

Docs missing. Please refer to https://github.com/JonnyBGod/loopback-sdk-builder/tree/new-ngrx/tests/ng2web/src for an example implementation.

### CODE REVIEW

**Comment by JonnyBGod** [comment]
Sorry for the commit mess. Think you can just Squash and Merge for simplicity.

**Comment by JonnyBGod** [comment]
Will add some simple documentation soon (might take a few days).

**Comment by RicardoVaranda** [comment]
Any timeline for when this will be added, great work by the way guys, Thanks for all the work put into it!

**Comment by JonnyBGod** [comment]
I believe this is pretty much done.
I do not expect to bring in any new breaking changes in the near future. Will only probably add a few small extra features regarding cleaning/reseting the state

**Comment by jmls** [comment]
/me claps hands with excitement .. can we get this merged ? please ? ;)

**Comment by jonathan-casarrubias** [comment]
Ok cool @JonnyBGod , I will merge and publish this once I get to my office.

I'm glad this is done since we will start working on a LB4 ready version soon, so I would not like to keep old PRs on

**Pull request merged**
