### PR TITLE
fix for Issue #371

### PR DESCRIPTION
**Pull request by jmls**
#### What type of pull request are you creating?
- [X] Bug Fix
- [ ] Enhancement
- [ ] Documentation

#### How many unit test did you write for this pull request?
none

Write a reason if none (e.g just fixed a typo):
program compiles under 2.2 with update, does not without

#### Please add a description for your pull request:

fixes the issue #371 _Operator '!==' cannot be applied to types_ compile error with typescript 2.2+

### CODE REVIEW

**Comment by jonathan-casarrubias** [comment]
Thanks for adding this patch, would you mind to add it to development instead of master?

Thanks

**Comment by lygstate** [comment]
This patch doesn't fixes #317, in Javascript world, there is no type with name 'array'
so typeof Value !== 'array' are invalid

**Comment by jonathan-casarrubias** [comment]
Lol this is getting complicated because there are many multiple issues to be fixed.

We need to fix the  typeof === 'array' (correct) changing it for Array.isArray but we also need to get rid of the typeof because of the compilation issue.

Maybe if this issue also adds the Array.isArray will include.

Or I can integrate 1 of these pull requests to development and then the other can update the other pull request with the new changes.

Please share your thoughts since you are fixing different issues on the same piece of code

**Comment by lygstate** [comment]
@jonathan-casarrubias, About the function _parseParam fixes, mine is the fixes, and for other, I am not sure what's the meaning.

**Comment by jonathan-casarrubias** [comment]
yes I'm just talking about _parseParam fixes. From this pull request we need

```js
let typeofValue:string = typeof value;
```

and its implementation, and from yours we need the

```js
Array.isArray()
```

but I see you @lygstate  also change the way the the params are build, so maybe we just need the Array.isArray from yours?

**Comment by lygstate** [comment]
@jonathan-casarrubias Yes, you can cherry pick that for fixes #371

**Pull request closed without merging**
