### PR TITLE
Observable interval

### PR DESCRIPTION
**Pull request by KingsDevelopment**
#### What type of pull request are you creating?
- [ ] Bug Fix
- [X] Enhancement
- [ ] Documentation

#### How many unit test did you write for this pull request?
None.

Write a reason if none (e.g just fixed a typo):
This won't fail if there are already unit tests for the imports.

#### Please add a description for your pull request:
This will add the interval to the Observable for each request.
See #292

### CODE REVIEW

**Comment by KingsDevelopment** [comment]
Might want to turn 
```
{ module: 'Observable', from: 'rxjs/Observable'},
```
Into
```
{ module: 'Observable', from: 'rxjs/rx'},
```
to allow any kind of operator to work out of the box.

**Comment by jonathan-casarrubias** [comment]
Hi @KingsDevelopment thanks for your contribution.

Actually, would you mind to update your pull request so we import all the operators? I was not keen to adding more than what is strictly used by the SDK, but now I truly believe your case is legit... using operators outside of the SDK should be a good feature to be supported.

**Comment by KingsDevelopment** [comment]
Allright, will update. give me a second (:

**Comment by KingsDevelopment** [comment]
Messed up commit name, sorry (used ticks)

**Comment by jonathan-casarrubias** [comment]
Not sure why but I'm also trying to update the real.time service to use this approach since it also returns observables.

But, I get an error when trying to import from rxjs/rx.

image

I believe it actually needs to be capitalized

image

**Comment by KingsDevelopment** [comment]
I am using the test environment, my IDE (Sublime) didn't show any errors, but yes it should be Rx. even though the tests wen't all right before pushing. Shouldn't they throw an error?

**Comment by KingsDevelopment** [comment]
both work for me:

!(https://puu.sh/t9NkC.png)

And

!(https://puu.sh/t9Nlx.png)

**Comment by jonathan-casarrubias** [comment]
Yes actually it should throw an error, not sure why it does not show the error for you.

I would rather use capitalized since seems to work for both of us

**Comment by KingsDevelopment** [comment]
Added capital R in case.

**Comment by jonathan-casarrubias** [comment]
Cool Thanks!

**Comment by KingsDevelopment** [comment]
Funny addon on this;
`.catch` is not working either. So when an error from the server is thrown, it's not catchable.

**Pull request merged**
