### PR TITLE
Handle arguments description arrays

### PR DESCRIPTION
**Pull request by viki53**
This is a quick and pretty dirty fix. 

But it works.

### CODE REVIEW

**Comment by jonathan-casarrubias** [comment]
@viki53 If you would like to appear on the list of contributors please share the following info:

1.- name
2.- email
3.- website or githubsite

Cheers
Jon

**Comment by viki53** [comment]
Sure

> Corentin Hatte
> contact@corentin-hatte.eu
> https://github.com/viki53

Thanks!

**Comment by jonathan-casarrubias** [comment]
This was added into the RC. version, I will close this pull request since it is already within the code.

Thanks for your contribution.

Cheers
Jon

**Comment by viki53** [comment]
Great!

⚠️  BTW, you added my GitHub profile to someone else in the [package.json](https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/package.json#L72) file.

**Comment by jonathan-casarrubias** [comment]
small little evil details lol...

I will fix that by next version then.

Cheers
Jon

**Pull request closed without merging**
