### PR TITLE
added silent option (-q) to suppress console output

### PR DESCRIPTION
**Pull request by jmls**
#### What type of pull request are you creating?
- [X] Enhancement

Write a reason if none (e.g just fixed a typo):

manual check to see if -q produces no console output

#### Please add a description for your pull request:

Added a new -q option to suppress console output during generation. If -q is selected, then -w is set to "enabled"

### CODE REVIEW

**Comment by jmls** [comment]
ping ... ;)

**Comment by jmls** [comment]
ping again - is it possible to get this merged ? I would prefer to use the official repo, not my fork. thanks.

**Comment by jonathan-casarrubias** [comment]
Would you mind to move this pull request to development instead of master?

**Comment by jmls** [comment]
closed as new pr to development branch

**Pull request closed without merging**
