### PR TITLE
fix(angular2): Auth Service to persist AccessToken issuedAt and ttl

### PR DESCRIPTION
**Pull request by JonnyBGod**
# How to contribute

I'm really glad you're reading this, volunteer developers to help this project are always welcome.

If you haven't already, follow me ([@johncasarrubias](irc://chat.freenode.net/opengovernment) on twitter). I want you to keep informed about new features and tutorials.

Here are some important resources:

  * [MEAN Expert Blog](http://mean.expert) tutorials about the MEAN Stack.
  * [WIKI](https://github.com/mean-expert-official/loopback-sdk-builder/wiki) official wiki documentation.
  * [Angular 2 Testing](https://angular.io/docs/ts/latest/guide/testing.html) official documentation for testing environment.
  * Bugs? [GitHub Issues](https://github.com/mean-expert-official/loopback-sdk-builder/issues) is where to report them

## Adding Issues
If you find any bug or enhancement, you are always welcome to create a [New Issue](https://github.com/mean-expert-official/loopback-sdk-builder/issues).

## Pull Request
If you would like to contribute by adding new features, enhancements or by fixing bugs; please consider that you need to create an issue prior your pull request. This is important for tracking purposes in CHANGELOG.

Please send a [GitHub Pull Request](https://github.com/mean-expert-official/loopback-sdk-builder/pull/new/master) with a clear list of what you've done (read more about [pull requests](http://help.github.com/pull-requests/)). When you send a pull request, we will love you forever if you include RSpec examples. We can always use more test coverage. Please make sure all of your commits are atomic (one feature per commit).

Always write a clear log message for your commits. One-line messages are fine for small changes, but bigger changes should look like this:

    $ git commit -m "A brief summary of the commit
    > 
    > A paragraph describing what changed and its impact."
    
Most of the times you will need to add a new test or we may not be able to integrate it. Though, there are some cases when you don't need to add a unit test, like fixing a typo, adding a missing type, etc.

## Testing

Tests are being created and excecuted by using the Angular-CLI Tool, please refer to the official documentation.

````sh
$ cd to/loopback-sdk-builder
$ npm test 
````

Thanks,
Jonathan Casarrubias, [MEAN Expert](http://mean.expert).

### CODE REVIEW

**Comment by jonathan-casarrubias** [comment]
Hey @JonnyBGod is good to see you back,

So... are these changes for loopback 3? I haven't check that out yet, if so.. we would need to maintain backwards support for 2 where is created.

**Comment by JonnyBGod** [comment]
Oh sorry I just realised this is for loopback-component-oauth.

Hold this for now. Let me study a bit more.

**Comment by JonnyBGod** [comment]
Ok so I changed a bit so that it can support both types AccessToken and OAuthAccessToken.

Fixed user service to save ttl as number.
And persist all relevant token data so that we can validate at any time at runtime.

Let me know if your don't like any of my options.

**Comment by JonnyBGod** [comment]
My changes here are to enable me to do something like:

```
checkLogginToken() {
    const token = this.auth.getToken();
    if (token && token.issuedAt && token.ttl) {
      let expires = new Date(token.issuedAt);
      expires.setSeconds(expires.getSeconds() + token.ttl);
      if (expires <= new Date()) {
        this.user.logout().subscribe(response => this.location.replaceState(''));
      }
    }
  }
```

at runtime.
Basically check if Token exists and not expired.

**Comment by jonathan-casarrubias** [comment]
Cool, would you mind to make the pull request to development instead of master?

**Comment by JonnyBGod** [comment]
Done https://github.com/mean-expert-official/loopback-sdk-builder/pull/222

**Pull request closed without merging**
