### PR TITLE
Fix for #401

### PR DESCRIPTION
**Pull request by fabianscheidt**
Params that are functions can't be route params. This check was missing and caused the bug in #401 with the newly introduced changePassword-method of loopbacks User-Class.

#### What type of pull request are you creating?
- [x ] Bug Fix
- [ ] Enhancement
- [ ] Documentation

### CODE REVIEW

**Comment by jonathan-casarrubias** [comment]
@fabianscheidt thanks a lot for this patch, would you mind to make it to the development branch instead of master? that way I can integrate with the rest of the work.

Cheers
Jon

**Comment by fabianscheidt** [comment]
@jonathan-casarrubias Sure. I changed the branch.

Greetings
Fabian

**Comment by jonathan-casarrubias** [comment]
@fabianscheidt, thanks for sending your patch, if you want me to add you into the contributor list please share the following:

name:
email:
website / github:

**Comment by fabianscheidt** [comment]
@jonathan-casarrubias Cool. I already sent you my data with pull request #319 ;-)

**Pull request merged**
