### PR TITLE
Fix #396: buildPropertyType method fix

### LINKED ISSUE #396: getModelDefinition() method does not expose exact type of the models
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [x] 2.1.0-rc.9 (2.1 Release Candidate n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Get Model Definition method should export "type" of the models however due to a bug in the code, api expects property.type, but have a check on property.type which is not existing.

### PR DESCRIPTION
**Pull request by bariscicek**
Changes argument for buildPropertyType to "type" and also update property.type
check to type.type check.

#### What type of pull request are you creating?
- [x] Bug Fix
- [ ] Enhancement
- [ ] Documentation

#### How many unit test did you write for this pull request?

Write a reason if none (e.g just fixed a typo):

#### Please add a description for your pull request:

### CODE REVIEW

**Comment by jonathan-casarrubias** [comment]
Hi @bariscicek thanks for sending this patch, but I need to add a couple of comments.

1.- You should always create pull request to the development branch instead of master, as stated in the contributors document.

2.- The buildPropertyType receives a Model property, therefore changing the parameter name from property to type is incorrect, honestly I'm not completely sure how we ended having the type variable in there but the actual change should be more like

````js
  function buildPropertyType(property) {
    if (!property.type) {
      return 'any';
    } 
    switch (typeof property.type) {
      case 'function':
        switch(property.type.name) {
          case 'String':
          case 'Number':
          case 'Boolean':
            return type.name.toLowerCase();
          case 'Date':
          case 'GeoPoint':
            return type.name;
          default:
            return 'any';
        }
      case 'object':
        if(Array.isArray(property.type)) {
            return `Array<${buildPropertyType(property.type[0])}>`
        }
        return 'object';
      default:
        return 'any';
    }
  }
````

If you update the pull request as described in the 2 points above I can allow this to be merged.

Regards

**Comment by bariscicek** [comment]
But calls to buildPropertyType are actualy "propery.type"s. Some examples:
`359 var geoPointType = buildPropertyType(model.properties[property].type);`
`390 output.push(`  "${property}"${isOptional}: ${buildPropertyType(meta.type)}${defaultValue};`);`

As you see property is not passed to the method, instead property.type directly.

**Comment by bariscicek** [comment]
Btw, checking the development branch, method is fixed using "type" as argument as expected. You can close the bug, but it should be really part of the 2.1 release imho.

Can you include method from development branch? Do I need to do anything?

**Comment by ryodeushii** [comment]
from index.js of generator
``` javascript
function buildPropertyType(property) {
    if (!property || !property.type) {
      return 'any';
    } 
    switch (typeof property.type) {
      case 'function':
        switch(property.type.name) {
          case 'String':
          case 'Number':
          case 'Boolean':
            return property.type.name.toLowerCase();
          case 'Date':
          case 'GeoPoint':
            return property.type.name;
          default:
            return 'any';
        }
      case 'object':
        if(Array.isArray(property.type)) {
            return `Array<${buildPropertyType(property.type[0])}>`
        }
        return 'object';
      default:
        return 'any';
    }
  }
```
We need only to change one row
From `        if(Array.isArray(type)) {` to `        if(Array.isArray(property.type)) {` and all works fine.

**Comment by jonathan-casarrubias** [comment]
@ryodeushii thanks for sharing the fix, there is a pull request implementing this, so I will merge that and I will close this PR now.

Cheers
Jon

**Pull request closed without merging**
