### PR TITLE
fixes issue where internal function params are included in client service declaration. see #310 and #317 

### LINKED ISSUE #310: Duplicate identifier 'options'
#### What type of issue are you creating?
- [ X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.0.10 (Stable)
- [X ] 2.1.0-rc.8
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Ran the generator, included the necessary sdk, and got the following error for each method defined in every Service
```
error TS2300: Duplicate identifier 'options'.
```
Upon looking further, it appears that the `options` parameter is being duplicated in the method signature. Example of a built-in one from loopback
```
  public findByIdAccessTokens(id: any, options: any = {}, fk: any, options: any = {}): Observable<any> {
    let _method: string = "GET";
    let _url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/Users/:id/accessTokens/:fk";
    let _routeParams: any = {
      id: id,
      fk: fk
    };
    let _postBody: any = {};
    let _urlParams: any = {};
    let result = this.request(_method, _url, _routeParams, _urlParams, _postBody);
    return result;
  }
```
Notice that `options` has been duplicated. This is happening to every method in every Service. Any ideas?

### PR DESCRIPTION
**Pull request by josephsnow**
#### What type of pull request are you creating?
- [X] Bug Fix
- [ ] Enhancement
- [ ] Documentation

#### How many unit test did you write for this pull request?
none - tried it with my own project to ensure it generated expected service declarations without internal function params.

Write a reason if none (e.g just fixed a typo):

#### Please add a description for your pull request:
fixes #310 and #317

### CODE REVIEW

**Comment by rodplata** [comment]
Awesome!! thanks!

**Comment by jonathan-casarrubias** [comment]
Hey Guys @josephsnow @rodplata thanks for working on this, but this issue have been already fixed within RC 8.3

Also, I'm not sure what I was thinking when I approved the `paramIsContext` implementation it misled you on the approach to fix this.

The correct implementation needs to be done within the utils.js file

https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/lib/utils.js#L71

This is because, the SDK Builder has been designed to create SDK for multiple different clients, not just Angular 2.... By fixing this issue within the Angular 2 scope is not correct since it is not framework specific, but a LoopBack specification, so we actually want this behaviour to be reflected in any new framework that we may support in a future.

Said that, I can assume you will understand why doing it within utils is the right approach.

I appreciate your efforts and I'm really looking forward for further contributions

Cheers
Jon

**Comment by rodplata** [comment]
But the `optionsFromRequest` it is not fixed even in RC 8.3, is it?

**Comment by jonathan-casarrubias** [comment]
Well yes, the only missing validation from this pull request is the `param.http === 'optionsFromRequest'`, which actually; neither I see within the loopback-swagger validation that @bajtos shared: https://github.com/strongloop/loopback-swagger/blob/2d4521a9e9d2e112541868f389fe924f6481e16a/lib/specgen/route-helper.js#L70-L84, so my question is if the optionsFromRequest is really required.

Anyway, after adding the snippet from the loopback-swagger the SDK worked again, are you still presenting issues?

**Comment by rodplata** [comment]
Yes it is required because `optionsFromRequest`, inject the accessToken into the options and can be read it in the EndPoints, so the client side do not need to provide them, 

if you include that, all methods that are executed in angular need to provide the options, and that's not necessarily needed 

and Yes, I still presenting issues, because all methods ask me to provide the `options` param at Angular but is not needed by Loopback (using loopback explorer, for example, does not ask for options)

**Comment by jonathan-casarrubias** [comment]
Ok I see the documentation that states this new arg type: https://loopback.io/doc/en/lb3/Using-current-context.html#annotate-options-parameter-in-remoting-metadata.

You can modify this pull request to add the optionsFromRequest validation within utils.js or I will do that by the next release.

**Comment by bajtos** [comment]
FWIW:

```js
http: 'optionsFromRequest'
```

is converted by LoopBack into 

```
http: function createOptionsViaModelMethod(ctx) { /*...*/ })
```

See [lib/model.js](https://github.com/strongloop/loopback/blob/304ecc4784c927be69caaa01a1b7344b169f0fa9/lib/model.js#L478-L482).

As a result, code inspecting remoting metadata (loopback-swagger, Angular2 SDK Builder) should never see the value `optionsFromRequest`.

**Comment by jonathan-casarrubias** [comment]
@bajtos, if Im understandig correct, that change `optionsFromRequest` to `function` is being being done prior code inspection? 

Right so that is the reason of why the snippet you provided does not verify for `optionsFromRequest` as argument because it already has been converted to function.

Is that correct?

**Comment by bajtos** [comment]
> that change optionsFromRequest to function is being being done prior code inspection?

yes.

> Right so that is the reason of why the snippet you provided does not verify for optionsFromRequest as argument because it already has been converted to function.

exactly! :)

**Comment by jonathan-casarrubias** [comment]
ok cool @bajtos  I have been analyzing the code and I see the filtering has been done for root model methods but not scope methods, maybe that is the reason that @rodplata still is presenting the issue. Will verify.

Thanks a lot again for your help @bajtos !!! I really appreciate it.

Cheers!
Jon

**Comment by jonathan-casarrubias** [comment]
Though I can not replicate @rodplata's issue, the test environment is already using the latests version of loopback and not even in the relationships is adding the options property as before.

**Comment by rodplata** [comment]
That's weird, look here is my example

in package.js
```
 "@mean-expert/loopback-sdk-builder": "^2.1.0-rc.8.3",
"loopback": "^3.0.0",
"loopback-boot": "^2.6.5",
"loopback-component-explorer": "^2.4.0",
"loopback-connector-cloudant": "^1.0.11",
```

My Remote Method:
```
Employee.remoteMethod(
'bySerial',
{
  accepts: [
    {arg: 'serial', type: 'string', required: true, http: {source: 'path'}},
    {arg: 'options', type: 'object', http: 'optionsFromRequest'},
  ],
  http: {path: '/bySerial/:serial/', verb: 'get'},
  returns: {arg: 'EMPLOYEE', type: 'Object'},
  description: 'Get the employee information using the employee serial',
});
```

This how it looks like in angular after SDK run:
```
/**
 * Get the employee information using the employee serial
 *
 * @param {string} serial 
 *
 * @param {object} options 
 *
 * @returns {object} An empty reference that will be
 *   populated with the actual data once the response is returned
 *   from the server.
 *
 * Data properties:
 *
 *  - `EMPLOYEE` – `{Object}` - 
 */
public bySerial(serial: any, options: any = {}): Observable<any> {
  let _method: string = "GET";
  let _url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
  "/employees/bySerial/:serial/";
  let _routeParams: any = {
    serial: serial
  };
  let _postBody: any = {};
  let _urlParams: any = {};
  let result = this.request(_method, _url, _routeParams, _urlParams, _postBody);
  return result;
}
```

as you can see, the options param is added to my remoteMethod

**Comment by jonathan-casarrubias** [comment]
ok cool @rodplata that actually is better info I can use, I will add a new remote method with a unit test with the exact configuration you shared and see what happen. If fails, then we have something to play around.

Cheers
Jon

**Comment by rodplata** [comment]
all the custom remote methods had options, this is just one of many examples

**Comment by jonathan-casarrubias** [comment]
lol ok, when you originally said **all methods** you implied that also persisted model methods, user methods had issues. Now you are scoping **all of your custom methods** which is different though.

For persisted model methods I mean the all of the built in CRUDs and for scope methods I mean the relational methods,  which I was trying to debug.

It does not really make a difference if you send another *custom remote method* I believe my question is clarified now.

I will add this particular case to the test environment as soon as I get the chance.

**Pull request closed without merging**
