### PR TITLE
The buildUrlParams should filter out routeParams & bodyParams.

### PR DESCRIPTION
**Pull request by lygstate**
To match the loopback semantics, when the bodyParams only have a single params,
then should use it directly.

### CODE REVIEW

**Comment by jonathan-casarrubias** [comment]
Hey @lygstate this looks good, I actually see your point... I didn't found the pattern before and that is why options and data were kind of hardcoded, but I just to confirm this semantic always works.

Could add a test by creating a new remoteMethod (Can be within Room Model) with a single post param and add a unit test for that to make sure it works.

There are 3 tests over the [room test](https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/tests/angular2/src/app/room-service.service.spec.ts#L84) that verifies other type of params to be correctly created I believe adding one in there would make sense.

Cheers
Jon

**Comment by lygstate** [comment]
I don't know how to use the test framework, I am not familiar with that yet, could you post a demo for me?

**Comment by jonathan-casarrubias** [comment]
Sure, there are basically 3 steps

inside `tests/angular2/common/models`

1.- Create a remoteMethod within the Room Model, there are already some remoteMethods you can use as example.
2.- Create a new unit test within the `tests/angular2/src/app/room-service.spec.ts`
https://github.com/mean-expert-official/loopback-sdk-builder/blob/master/tests/angular2/src/app/room-service.service.spec.ts#L84

You can test by running

````sh
$ node loopback/server.js && ng test
````

All the tests should pass.

Cheers!!
Jon

**Comment by lygstate** [comment]
can you add the ci first

**Comment by jonathan-casarrubias** [comment]
Hi @lygstate I have seen your updates, I like some of them but I'm concerned about others, it seems you are working considering just 1 scope of work, but the builder works in multiple different cases.

In order to accept this you would need to make sure all of the tests passes, because I'm kind of feeling that with your changes more than 1 test will fail.

As a practice you should not be refactoring so much without testing that you did not broke anything.

Please place your self within the `tests/angular2` then `npm install` to get all the dependencies and do the test.

If you don't have it already, you will need the angular-cli tool to run the tests

````sh
$ npm install -g angular-cli
````


Please consider that I feel many of your changes are good ideas, but I can't accept these if any of the previous tests do not pass, or if you don't create new tests that verifies your use case.

Regards
Jon

**Comment by jonathan-casarrubias** [comment]
@lygstate  I'm about to release a new version, I will create the tests for this and make sure it does not break anything else. I hope this will help you understand the Test Suit.

Regards
Jon

**Pull request merged**
