### PR TITLE
fix(angular2): Auth Service to persist AccessToken issuedAt and ttl

### PR DESCRIPTION
**Pull request by JonnyBGod**
# How to contribute

I'm really glad you're reading this, volunteer developers to help this project are always welcome.

If you haven't already, follow me ([@johncasarrubias](irc://chat.freenode.net/opengovernment) on twitter). I want you to keep informed about new features and tutorials.

Here are some important resources:

  * [MEAN Expert Blog](http://mean.expert) tutorials about the MEAN Stack.
  * [WIKI](https://github.com/mean-expert-official/loopback-sdk-builder/wiki) official wiki documentation.
  * [Angular 2 Testing](https://angular.io/docs/ts/latest/guide/testing.html) official documentation for testing environment.
  * Bugs? [GitHub Issues](https://github.com/mean-expert-official/loopback-sdk-builder/issues) is where to report them

## Adding Issues
If you find any bug or enhancement, you are always welcome to create a [New Issue](https://github.com/mean-expert-official/loopback-sdk-builder/issues).

## Pull Request
If you would like to contribute by adding new features, enhancements or by fixing bugs; please consider that you need to create an issue prior your pull request. This is important for tracking purposes in CHANGELOG.

Please send a [GitHub Pull Request](https://github.com/mean-expert-official/loopback-sdk-builder/pull/new/master) with a clear list of what you've done (read more about [pull requests](http://help.github.com/pull-requests/)). When you send a pull request, we will love you forever if you include RSpec examples. We can always use more test coverage. Please make sure all of your commits are atomic (one feature per commit).

Always write a clear log message for your commits. One-line messages are fine for small changes, but bigger changes should look like this:

    $ git commit -m "A brief summary of the commit
    > 
    > A paragraph describing what changed and its impact."
    
Most of the times you will need to add a new test or we may not be able to integrate it. Though, there are some cases when you don't need to add a unit test, like fixing a typo, adding a missing type, etc.

## Testing

Tests are being created and excecuted by using the Angular-CLI Tool, please refer to the official documentation.

````sh
$ cd to/loopback-sdk-builder
$ npm test 
````

Thanks,
Jonathan Casarrubias, [MEAN Expert](http://mean.expert).

### CODE REVIEW

**Comment by jonathan-casarrubias** [comment]
Hey @JonnyBGod I'm testing your patch but I get a compilation issue because of the following line:
````js
response.ttl = parseInt(response.ttl); <--- Generates a compilation issue
````

That is because the response.ttl  has a number type, so parseInt is expecting a string.. Right now I'm fixing it by commenting that line.

We may want to change the response to any? not sure, lets figure out the best approach

**Comment by JonnyBGod** [comment]
Oh ok. For some reason I did not get any compilation error.

Problem there is that response from server is a string and we need it to be a number to calculate dates.

Yes one option would be to make it ```ttl: number | string;```.

**Comment by JonnyBGod** [comment]
Oh I remember what I did and forgot to commit...

```
.map(
          (response: any) => {
```

**Comment by JonnyBGod** [comment]
whant me to PR it or you will change?

**Comment by JonnyBGod** [comment]
I think this souled the better than changing model as the reality is that the response is not actually conforming with model.

**Comment by jonathan-casarrubias** [comment]
Yes I think for now is ok using any, I can add it

**Pull request merged**
